# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MoneyloverCli < Formula
  desc "CLI for Money Lover personal finance app"
  homepage "https://github.com/syahidfrd/moneylover-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/syahidfrd/moneylover-cli/releases/download/v0.4.0/moneylover-cli_darwin_amd64.tar.gz"
      sha256 "460b8d54efdeb1d9099018949a01f94037f5a3f6efee417cb13521b9401a4598"

      define_method(:install) do
        bin.install "moneylover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/syahidfrd/moneylover-cli/releases/download/v0.4.0/moneylover-cli_darwin_arm64.tar.gz"
      sha256 "3d4b2d0f4c741b56e0ebeafe03245577dc4a12dc2ad4174e5597f3300a0fb35c"

      define_method(:install) do
        bin.install "moneylover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/syahidfrd/moneylover-cli/releases/download/v0.4.0/moneylover-cli_linux_amd64.tar.gz"
      sha256 "fa2cbfcc728e6948c9b948e10e28776724b7e2ba1be726d4bd6c4e5041be0b6c"
      define_method(:install) do
        bin.install "moneylover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/syahidfrd/moneylover-cli/releases/download/v0.4.0/moneylover-cli_linux_arm64.tar.gz"
      sha256 "2b160681077c78c26ad1747059ac421510716bff0b230b4849382b8f7dabfc21"
      define_method(:install) do
        bin.install "moneylover"
      end
    end
  end
end
