# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MoneyloverCli < Formula
  desc "CLI for Money Lover personal finance app"
  homepage "https://github.com/syahidfrd/moneylover-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/syahidfrd/moneylover-cli/releases/download/v0.2.0/moneylover-cli_darwin_amd64.tar.gz"
      sha256 "5ceff81a7eeca9b76e88efd788d5473de2d3a2219e55b09d7706ea42dce3daa9"

      define_method(:install) do
        bin.install "moneylover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/syahidfrd/moneylover-cli/releases/download/v0.2.0/moneylover-cli_darwin_arm64.tar.gz"
      sha256 "56c955ca016fab53b1aea5da63102609115c8c6aab8846ebf510112cfaf6b1be"

      define_method(:install) do
        bin.install "moneylover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/syahidfrd/moneylover-cli/releases/download/v0.2.0/moneylover-cli_linux_amd64.tar.gz"
      sha256 "8ef086052b2886bd5c88dc14c9487ed83e76662bb8e121983e2a6b736c56042c"
      define_method(:install) do
        bin.install "moneylover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/syahidfrd/moneylover-cli/releases/download/v0.2.0/moneylover-cli_linux_arm64.tar.gz"
      sha256 "58ee238ce4f1b758bc3411b482c451f0e0eb166ef8c530538bd1b033dbdb6741"
      define_method(:install) do
        bin.install "moneylover"
      end
    end
  end
end
